USE [BoardGameArchive]
GO 
---tbloyun TABLOSUNDA FAZLA VERI OLMADIGI ICIN YENI BIR TABLO OLSUTURULUR VE WHILE DONGUSU VERI SAYISI ARTTIRILIR
IF OBJECT_ID('dbo.IndexExampleTable')  IS NOT NULL 
DROP TABLE IndexExampleTable 
GO 
CREATE TABLE IndexexampleTable(x INT PRIMARY KEY , y varchar(150))
go 
DECLARE @x int = 1, @y int 
DECLARE @value varchar(150) 

WHILE @x<=100000 
BEGIN
IF @x>50000
SET @value = 'Chess ' 
ELSE 
BEGIN 
SET @y=(CONVERT(INT ,ROUND(RAND()*10,0)) %10)+1 
SELECT @value= adi from tblOyun where id=@y 
end 
INSERT INTO IndexexampleTable VALUES (@x,@value)
SET @x=@x+1
END 

--OLUSTURUAN TABLONUN DENEMESI 
SELECT * FROM IndexexampleTable 


----INDEX CALISTIRILMADAN ONCE 
-- BU KISIMDA INDEX OLUSTRULMADAN ONCE SORGULAR GIRILIR 
-- IKI TANE SORGU VARDIR BIRINCISI INDEX YAPILARAK TEKRAR SORGULATACAK DIGERI ISE INDEX OLMADAN TEKRAR SORGULANACAK 
--ARADAKI FARKI GORMEK ICIN  BU ISLEM YAPILIR 
SET STATISTICS IO ON 
SET STATISTICS TIME ON 
SELECT *FROM IndexexampleTable WHERE x>50000 
SELECT *FROM IndexexampleTable WHERE y='Chess'

SET STATISTICS IO OFF 
SET STATISTICS TIME OFF 

--INDEX OLDUKTAN SONRA 
--NONCLUSTERED INDEX OLUSTURULUR 

IF OBJECT_ID('dbo.IndexDeneme') IS NOT NULL 
BEGIN 
DROP INDEX IndexDeneme on IndexExampleTable
end 
go 
CREATE NONCLUSTERED INDEX IndexDeneme on IndexExampleTable(y)
WITH( PAD_INDEX = ON ,FILLFACTOR= 90 ,DROP_EXISTING=OFF) 

SET STATISTICS IO ON 
SET STATISTICS TIME ON 
SELECT *FROM IndexexampleTable WHERE x>50000 
SELECT *FROM IndexexampleTable WHERE y='Chess'

SET STATISTICS IO OFF 
SET STATISTICS TIME OFF 